apiVersion: v1
kind: Service
metadata:
  name: {{ include "palivane.fullname" . }}
  labels: {{- include "palivane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: palivane
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {port: {{ .Values.service.port }}, targetPort: http, name: http}
