#!/usr/bin/env bash
# Run Palivane natively on this machine — NO Docker.
#
# Python venv (.venv-local) + SQLite + the prebuilt SPA, all served single-origin on
# http://localhost:8088. First run seeds a demo org (admin@demo.local / changeme123).
# Ctrl-C to stop.  See RUNNING-LOCALLY.md for setup + details.
#
#   ./run-local.sh            # start (seeds on first run)
#   ./run-local.sh --seed     # force-reseed the demo data
#   PORT=9000 ./run-local.sh  # use a different port
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
VENV="$ROOT/.venv-local"
PY="$VENV/bin/python"
PORT="${PORT:-8088}"

[ -x "$PY" ] || { echo "!! venv missing ($VENV). Run the one-time setup in RUNNING-LOCALLY.md first." >&2; exit 1; }
[ -f "$ROOT/frontend/dist/index.html" ] || { echo "!! SPA not built. Run: (cd frontend && npm ci && npm run build)" >&2; exit 1; }

# Persist config + a generated secret across restarts (so logins survive). Gitignored.
ENVFILE="$ROOT/.env.local"
if [ ! -f "$ENVFILE" ]; then
  cat > "$ENVFILE" <<EOF
# Generated by run-local.sh — local-only, never committed.
PALIVANE_SECRET_KEY=$("$PY" -c 'import secrets;print(secrets.token_hex(32))')
DATABASE_URL=sqlite:///$ROOT/palivane-local.db
PALIVANE_STATIC_DIR=$ROOT/frontend/dist
PALIVANE_PUBLIC_URL=http://localhost:$PORT
CORS_ORIGINS=http://localhost:$PORT
SEED_ADMIN_EMAIL=admin@demo.local
SEED_ADMIN_PASSWORD=changeme123
EOF
  echo "==> wrote $ENVFILE (generated a PALIVANE_SECRET_KEY)"
fi
# shellcheck disable=SC1090
set -a; . "$ENVFILE"; set +a

FRESH=0; [ -f "$ROOT/palivane-local.db" ] || FRESH=1

cd "$ROOT/backend"
echo "==> alembic upgrade head"
"$VENV/bin/alembic" upgrade head

if [ "${1:-}" = "--seed" ] || [ "$FRESH" = 1 ]; then
  echo "==> seeding demo data (login: ${SEED_ADMIN_EMAIL} / ${SEED_ADMIN_PASSWORD})"
  "$PY" -m app.seed || echo "!! seed skipped/failed (continuing)"
fi

echo "==> Palivane running at http://localhost:$PORT   (Ctrl-C to stop)"
exec "$VENV/bin/uvicorn" app.main:app --host 127.0.0.1 --port "$PORT"
