"""enrollment tokens

Revision ID: 0da9f945dbb6
Revises: d1a4c6e839f0
Create Date: 2026-07-02 13:20:35.077469
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0da9f945dbb6'
down_revision: Union[str, None] = 'd1a4c6e839f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenant_oidc', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_oidc_tenant'), type_='unique')

    with op.batch_alter_table('tenant_saml', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_saml_tenant'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_saml', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_saml_tenant'), ['tenant_id'])

    with op.batch_alter_table('tenant_oidc', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_oidc_tenant'), ['tenant_id'])

    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_prefix'))
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_id'))

    op.drop_table('enrollment_tokens')
    # ### end Alembic commands ###
