"""initial schema

Revision ID: 434ec8de7f54
Revises: 
Create Date: 2026-06-18 13:54:45.748378
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '434ec8de7f54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('recommended_action', sa.String(length=32), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('attack_intent', sa.Boolean(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('judge_used', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_ai_generated'), ['ai_generated'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_attack_intent'), ['attack_intent'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_surface'), ['surface'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_findings_surface'))
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_risk_score'))
        batch_op.drop_index(batch_op.f('ix_findings_id'))
        batch_op.drop_index(batch_op.f('ix_findings_created_at'))
        batch_op.drop_index(batch_op.f('ix_findings_attack_intent'))
        batch_op.drop_index(batch_op.f('ix_findings_ai_generated'))

    op.drop_table('findings')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
